apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-webapp
  template:
    metadata:
      labels:
        app: weather-webapp
    spec:
      containers:
      - name: weather-webapp
        image: devopsgoofy/weather-webapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: weather-webapp-service
spec:
  type: NodePort
  selector:
    app: weather-webapp
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
