apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          env:
            - name: NGINX_USER
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: NGINX_USER
            - name: NGINX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: NGINX_PASS
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
