# works only for 12 hours after getting this command:
# aws ecr get-login-password --region eu-central-1 | base64
apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: aws-eu-central-1-helm-ecr
  namespace: argocd
type: Opaque
data:
  # True
  enableOCI: dHJ1ZQ==
  # 2games1helm
  name: MmdhbWVzMWhlbG0=
  # secret
  password: <ECR-TOKEN>
  # default
  project: ZGVmYXVsdA==
  # helm
  type: aGVsbQ==
  # 993467604613.dkr.ecr.eu-central-1.amazonaws.com
  url: OTkzNDY3NjA0NjEzLmRrci5lY3IuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20=
  # AWS
  username: QVdT
