apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: argocd-cronjob-sa
  namespace: argocd
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io