apiVersion: v1
kind: Secret
metadata:
  name: spinnaker-service-account-token
  namespace: spinnaker
  annotations:
    kubernetes.io/service-account.name: spinnaker-service-account
type: kubernetes.io/service-account-token
