apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: eu-central-1

managedNodeGroups:
  - name: eks-workers
    desiredCapacity: 2
    instanceType: t2.medium
    amiFamily: Ubuntu2204
    volumeSize: 16
    ssh:
      allow: true
      publicKeyName: k8s
